class Collection {
  int? id; // Primary key (auto-generated by SQLite)
  String accountNumber;
  String accountName;
  double amount;
  String type;

  Collection({
    this.id,
    required this.accountNumber,
    required this.accountName,
    required this.amount,
    required this.type,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'accountNumber': accountNumber,
      'accountName': accountName,
      'amount': amount,
      'type': type,
    };
  }
}
